{% set name = "dbt-bigquery" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-bigquery-{{ version }}.tar.gz
  sha256: aabc9a0acdc602791d57fd65086c4d86d8ca167ce6fc36c696c04ec557594eb7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    # Ref: <https://www.marcelotrevisani.com/grayskull>
    - dbt-core >=1.1.0,<1.2  # Changed ==1.1.* to <1.2
    - google-api-core >=1.16.0,<3
    - google-cloud-bigquery >=1.25.0,<3
    - google-cloud-core >=1.3.0,<3
    - googleapis-common-protos >=1.6.0,<2
    - protobuf >=3.13.0,<4
    - python >=3.7

test:
  imports:
    - dbt
    - dbt.adapters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-bigquery
  summary: The BigQuery adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - maresb
    - thewchan
